### ISSUE TITLE
Return value of Vich\UploaderBundle\Mapping\PropertyMapping::getFile() must be an instance of Symfony\Component\HttpFoundation\File\File or null, string returned

### ISSUE THREAD

**Issue by MarkoM91** [dustin10/VichUploaderBundle#1037]

**Comment by amstr4d** [comment]
I got the same problem. How did you resolved it ? Thanks

**Comment by LUDZpro** [comment]
you will need to remove the ``getImageFile()`` method. 
you won't need it because you will use the ``function getImage()`` to get the url of the image and use it to display the image. 
and don't forget to link the two with the fileNameProperty attribute in Vich\UploadableField  class constructor


```
// this is your image url
/**
     * @ORM\Column(type="string", length=255)
     */
private $thumbnail;
```

```
// vichUploadable file
/**
* @Vich\UploadableField(mapping="brands",fileNameProperty="thumbnail")
*/
public $thumbnailFile;
```

and you will need the setter to edit an ORM proprety so that Doctrine detect that there is a change in the Entity, for example UpdatedAt . as @MarkoM91 did in his example. 

```
public function setThumbnailFile( $file): self
{
     $this->thumbnailFile = $file;
     if($file) $this->updatedAt = new \DateTime();
     return $this;
}
```

**Comment by TachafineAITTouda** [comment]
you will need to remove the ``getImageFile()`` method. 
you won't need it because you will use the ``function getImage()`` to get the url of the image and use it to display the image. 
and don't forget to link the two with the fileNameProperty attribute in Vich\UploadableField  class constructor


```
// this is your image url
/**
     * @ORM\Column(type="string", length=255)
     */
private $thumbnail;
```

```
// vichUploadable file
/**
* @Vich\UploadableField(mapping="brands",fileNameProperty="thumbnail")
*/
public $thumbnailFile;
```

and you will need the setter to edit an ORM proprety so that Doctrine detect that there is a change in the Entity, create UpdatedAt proprety as @MarkoM91 did in his example. 

```
public function setThumbnailFile( $file): self
{
     $this->thumbnailFile = $file;
     if($file) $this->updatedAt = new \DateTime();
     return $this;
}
```
