### ISSUE TITLE
Default visibility ACL

### ISSUE THREAD

**Issue by tristanbes** [dustin10/VichUploaderBundle#1149]
|    Q            |   A
|---------------- | ------
| Bundle version  | 1.15
| Symfony version | 4.4
| PHP version     | 7.4

### Support Question

Hello,

I'm using VichUploaderBundle + thephpleague/flysystem-bundle + AsyncAws + s3 client (all fresh install from today)

After reading the docs, no actors are covering the default visibility when creating an object inside the bucket;
For example, the uploaded image is inside the bucket, but has a private ACL, preventing a public access.

My question is:
- How to set the default visibility to public (`public-read`) for images uploaded by VichUploaderBundle ?

Thank you 👍 

![Storage___Bucket___Explorer_-_Scaleway_Console](https://user-images.githubusercontent.com/346010/92262503-8aac0800-eedb-11ea-9039-25b5355bf213.png)

**Comment by garak** [comment]
I don't think this is something related to VichUploaderBundle

**Comment by tristanbes** [comment]
ok, will try to poke around on the related issue on the flysystem bundle then. thanks

**Comment by craigh** [comment]
@garak 

> I don't think this is something related to VichUploaderBundle

While the top-level bucket access can be set by the storage system (e.g. flysystem), it is apparently not possible to set file-level access.

for example, in `\Vich\UploaderBundle\Storage\FlysystemStorage::doUpload` the stream is written like so:

            $fs->writeStream($path, $stream, [
                'mimetype' => $file->getMimeType(),
            ]);

but in order to set a file-level ACL you would need to do:

            $fs->writeStream($path, $stream, [
                'mimetype' => $file->getMimeType(),
                'visibility' => 'public' // or 'private'
            ]);

This setting is specific to AWS S3 so I don't know how this could be abstracted to other storage providers. 

I considered decorating the `FlysystemStorage` class and altering the  `doUpload` method to accomplish this, but then the question of where the setting should come from matters. I considered adding a property to the `UploadableField` mapping annotation, (e.g. `visibility`). This would allow a setting per field, but not individual files.

Any ideas?

Current solution I guess is to use a different flysystem filesystem per mapping based on visibility preferences for that field, but still this does not allow file-level settings.
