### ISSUE TITLE
PropertyMapping should not be internal

### ISSUE THREAD

**Issue by kappaj** [dustin10/VichUploaderBundle#1260]
### Feature Request

It is no feature, only a small improvement I think ;-)

When you build an custom namer you have to implement the NamerInterface. So you have to create the method `name()`.
One parameter is of type `PropertyMapping`. But this class is internal. So the IDE shows a warning. 

![PropertyMapping](https://user-images.githubusercontent.com/11064439/149155455-d1ec7bed-a4b4-442e-9c94-6b0af26068e0.PNG)

Solution:

The class PropertyMapping should not be internal.

**Comment by garak** [comment]
Thanks for your contribution.
Here's a general suggestion: when you find a problem, you should check if the same problem was already solved, e.g. if the same issue was already opened. Looking into currently open issues isn't enough, since it can happen (and it happened in this case) that the issue was already closed (even if the solution is still unavailable in a stable branch).

See #1253
