### ISSUE TITLE
php8 attributes doesn't work

### ISSUE THREAD

**Issue by DoudouPike** [dustin10/VichUploaderBundle#1272]
### Bug Report

|    Q            |   A
|---------------- | ------
| BC Break        | no
| Bundle version  | 1.19.0
| Symfony version | 5.3.13
| PHP version     | 8.0.15

#### Summary

Works with annotations, not with attributes

#### Current behavior

I have a File entity with Vich annotations, an events subscriber who listen postUpload & preRemove VichEvents.
On test env, I have a fixture that generate tmp files and multiple File instances.
All of this run on docker.
And all works!

But when I switch annotations to php8 attributes, Vich won't work anymore, event aren't triggered.. even I erase cache.

> All my other attrbitutes (Constraints, Doctrine...) works well.

**Comment by garak** [comment]
Please provide a reproducer

**Comment by martinsoenen** [comment]
Hello,

Here is a reproducer.

Entity :
`
<?php

namespace App\Entity;

use App\Repository\BlablaRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\Validator\Constraints as Assert;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

#[Vich\Uploadable]
#[ORM\Entity(repositoryClass: BlablaRepository::class)]
/**
 * @Vich\Uploadable
 */
class Blabla
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 10)]
    #[Assert\Length(
        min: 1,
        max: 10,
        minMessage: "The blabla cannot be blank",
        maxMessage: "The blabla cannot exceed a length of 10 characters"
    )]
    private $blabla;

    #[ORM\Column(type: 'string', length: 255)]
    private $file;

    #[Vich\UploadableField(
        mapping: "blablas",
        fileNameProperty: "file"
    )]
    public $patchFile;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getBlabla(): ?string
    {
        return $this->blabla;
    }

    public function setBlabla(string $blabla): self
    {
        $this->blabla = $blabla;

        return $this;
    }

    public function getFile(): ?string
    {
        return $this->file;
    }

    public function setFile(string $file): self
    {
        $this->file = $file;

        return $this;
    }

    public function setPatchFile(File $file = null)
    {
        $this->file = $file;

        // VERY IMPORTANT:
        // It is required that at least one field changes if you are using Doctrine,
        // otherwise the event listeners won't be called and the file is lost
        if ($file) {
            $this->blabla = $this->blabla;
        }
    }

    public function getImageFile()
    {
        return $this->file;
    }
}
`

vich_uploader.yaml : 
`
vich_uploader:
    db_driver: orm

    mappings:
        blablas:
            uri_prefix: /uploads/blablas
            upload_destination: '%kernel.project_dir%/public/uploads/blablas'
`

When we do this, we get the following error : 
`
The class "App\Entity\Blabla" is not uploadable. If you use annotations to configure VichUploaderBundle, you probably just forgot to add `@Vich\Uploadable` on top of your entity. If you don't use annotations, check that the configuration files are in the right place. In both cases, clearing the cache can also solve the issue.
`

The problem is that the bundle does not understand when the annotation is like `#[Vich\Uploadable]` instead of `@Vich\Uploadable`

**Comment by garak** [comment]
Not clear what's "when we do this". And your entity has both annotations and attributes

**Comment by garak** [comment]
Anyway, this is not enough. I need a project that I can just run, with instructions on what to do to reproduce your problem.
A repository would be the best option

**Comment by martinsoenen** [comment]
Ah yes sorry for annotations and attributes, I was writing this while testing with annotations and I forgot to remove it.

Anyway, I can do a repo, but actually the problem is just that if I use attributes instead of annotations it does not work. With attributes, I have the error I posted above, if I use annotations I don't have any problem. I think it is the same for the creator of the issue.

For information, I am using PHP 8.1 and the last version of EasyAdmin & VichUploader.

**Comment by martinsoenen** [comment]
I'm sorry I can't do a reproducer repo atm.

But you can try by installing a fresh Symfony, EasyAdmin and VichUploader install. If you create your entity by use PHP attributes (not annotations) you'll get the problem

**Comment by garak** [comment]
Did you try *without* EasyAdmin?

**Comment by martinsoenen** [comment]
I just tried and I have the same error
When I put the `VichImageType` or `VichFileType` in my form, it instantly displays this error

**Comment by everio** [comment]
Here the right configuration for php annotations  : 
```
vich_uploader:    
    metadata:
        type: attribute
```

**Comment by DoudouPike** [comment]
Thx @everio it works now. 

The documentation should be modified, the line "Don't forget to add vich_uploader.metadata.type: attribute to the config." should be just below "Or, with PHP 8 attributes :". Actually its on the part that explain how to add an EmbeddedFile property.
