### ISSUE TITLE
Broken metadata when updated Doctrine to 2.8.0

### ISSUE THREAD

**Issue by sc0rp10** [dustin10/VichUploaderBundle#1344]
### Bug Report

|    Q            |   A
|---------------- | ------
| BC Break        | no
| Bundle version  |  2.0.1
| Symfony version | 6.2.2
| PHP version     | 8.2.0

#### Summary

`Vich\UploaderBundle\Exception\NotUploadableException` on all entities after update Doctrine to 2.8.0

#### Current behavior

All the uploadable entities are broken with `Vich\UploaderBundle\Exception\NotUploadableException`

doctrine/doctrine-bundle doesn't require `doctrine/annotations` anymore which breaks metadata reader, to fix it I've added `doctrine/annotations:1.14.1` to dependencies list, but it seems not to be a correct solution. It'd be nice if we can drop requirement of deprecated library.

#### How to reproduce

composer require doctrine/doctrine-bundle:2.8.0 and refer to any uploadable field of any uploadable entity.

#### Expected behavior

uploadable entities works.

**Comment by garak** [comment]
I guess that the correct solution is not using annotations:  attributes could be an easy alternate solution.
By the way, version 2 only supports annotations to ease the upgrade from previous versions.

Can you please open a PR to propose an integration to documentation?

**Comment by sc0rp10** [comment]
Hi, @garak 
Forgot to say: I'm using attributes only:

```
$ ./bin/console debug:config vich_uploader metadata

Current configuration for "vich_uploader.metadata"
==================================================

type: attribute
cache: file
file_cache:
    dir: /foo/var/cache/dev/vich_uploader
auto_detection: true
directories: {  }
```

**Comment by garak** [comment]
I guess that, in this case, updating docs is not enough: we need to update composer.json as well, adding `doctrine/annotations` to the list of suggested packages.
Still, a PR would be appreciated.

**Comment by andyexeter** [comment]
This is appears to be cause by the following conditional:

https://github.com/dustin10/VichUploaderBundle/blob/b0b17cc7e44d57a6e3bf82468289ad4f3ee8c622/src/DependencyInjection/Compiler/RegisterMappingDriversPass.php#L21

The `annotation_reader` service isn't created when the `doctrine/annotations` isn't present. However, the service is _not_ required to read attributes.

I confirmed this by changing the line to:

```php
if (true || $container->has('annotation_reader')) {
```

And everything started working again.

**Comment by garak** [comment]
Well spotted!
So now we need to change that check, do you have any idea about it?

**Comment by andyexeter** [comment]
I think we'd need to add the metadata.type config as a parameter, so we can check whether it's set to `attribute` or `annotation` - something like this maybe?:

```php
# src/DependencyInjection/VichUploaderExtension.php

public function load(array $configs, ContainerBuilder $container): void
{
    // ...
    $container->setParameter('vich_uploader.metadata_type', $config['metadata']['type']);
    // ...
}
```

Then we could change the check to: 

```php
$metaDataType = $container->getParameter('vich_uploader.metadata_type');

if ($metaDataType === 'attribute' || ($metaDataType === 'annotation' && $container->has('annotation_reader'))) {
```

WDYT? Happy to create a PR for this.

**Comment by garak** [comment]
I think that my knowledge of annotations and attributes is not enough to fully understand the problem here.
Unfortunately, I don't have any actual projects using them, since I moved to XML mapping many years ago.
Maybe @mathieupetrini can shed some light here?

**Comment by andyexeter** [comment]
@garak I closed the PR for the reasons mentioned in it.

This bundle's [AttributeReader](https://github.com/dustin10/VichUploaderBundle/blob/afb438d29487056c6b8bc2014d3d8d28ff7b4721/src/Metadata/Driver/AttributeReader.php) implements `Doctrine\Common\Annotations\Reader` which is part of the `doctrine/annotations` package - so it seems that package is for both annotations _and_ attributes to work.

**Comment by garak** [comment]
I can only guess that annotations are not strictly required to use attributes, otherwise Doctrine wouldn't have dropped it.

**Comment by andyexeter** [comment]
That's correct, the doctrine/orm package now comes with its own `AttributeReader` and doesn't use `doctrine/annotations`: https://github.com/doctrine/orm/blob/ed56f42cd50a17fd00f601d57912f41769123134/lib/Doctrine/ORM/Mapping/Driver/AttributeReader.php

Seeing as this bundle requires PHP >= 8.1, it might be an idea to deprecate annotations support in the next minor release and remove it in a major release?

**Comment by feymo** [comment]
A possible solution could be to implement a `ReaderInterface` directly **in** the bundle (with the same structure as the `Doctrine\Common\Annotations\Reader`) and rely on this one instead.
Doing so, we won't need to add an extra dependency to `doctrine/annotations`.
What do you think ? I can create a PR for such approach 👍🏼

**Comment by garak** [comment]
@feymo yes please

**Comment by feymo** [comment]
It seems to be trickier than i initially thought...
As mentioned in #1346, the `Reader` interface from `doctrine/annotations` is used in many places, for attributes support but also for annotations.
And because of the bundle choice to offer support for both annotations **AND** attributes, it would be a lot of work to rewrite dedicated interfaces for both approaches. 😞 
Since the bundle requirement for PHP version is `>= 8.1`, i agree with @andyexeter proposal : 
- deprecate annotations support & add doctrine/annotations to suggested package (even if in a project with doctrine-bundle >=2.8, it would be more a requirement than a suggestion 😄 )
- in the next major version, drop annotations support for only attributes.
Doing so, the needed work would be done only on the PHP attributes support, which would make imo more sense

**Comment by garak** [comment]
So, just to be clear, does rewriting the interfaces only for attributes would affect the way we support annotations now?

**Comment by feymo** [comment]
Short answer: no.
Long answer: Starting from version `2.8` of `doctrine-bundle` (released Dec. 29th 2022), the `doctrine/annotations` bundle has been removed from the requirements. Which means that **every project** with a `doctrine-bundle` version `>= 2.8` that does not require on their own the `doctrine/annotations` bundle will not be able to use VichUploader not matter their choice of configuration (annotation and attributes) since the Reader interface will not be found. 😞

**Comment by garak** [comment]
That's true only for projects that use VichUploaderBundle with annotations or attributes (configurations with XML or YAML are not affected).
Anyway, the problem of missing annotations library can be easily solved by suggesting it and updating the documentation.

The aim now is not to force projects using attributes to install the annotations library, that's a bit weird (from the point of view of the users). It would be best if we could achieve it in a minor version.

**Comment by feymo** [comment]
Yes, indeed, i was talking about projects using annotations or attributes 👍🏼 
Sure, the documentation can be updated with the suggestion, but even projects using attributes would have to install `doctrine/annotations` since the interface is also used in the bundle for the annotations part

**Comment by garak** [comment]
And so we go back to the previous question: can we change the way we define attributes to avoid using annotations?

**Comment by feymo** [comment]
i'm still trying to find a way but so far, it doesn't seems possible. The support of annotations and attributes are linked to one another, since they both rely on the `Reader` interface.
As far as i know, there is 2 options for people using annotations or attributes in their project with doctrine-bundle >= 2.8 :
- Suggest the installation of `doctrine/annotations`, no matter the config chosen between annotations or attributes (because the interface is used in the 2 configs, and both are loaded by the container)
- Change the way attributes AND annotations are defined to avoid rely on the `Reader` interface provided by Doctrine through `doctrine-bundle`.

**Comment by garak** [comment]
Can we replace our internal `Vich\UploaderBundle\Metadata\Driver\AttributeReader` with `Doctrine\ORM\Mapping\Driver\AttributeReader`?

**Comment by sc0rp10** [comment]
Just saying: `doctrine/annotations` de-facto marked as deprecated: "library is considered feature complete, and should receive exclusively bugfixes and security fixes.", there are no guarantees that library will work with newer PHP versions and other requirements. IMO we should replace it as soon as possible with own independent implementation of metadata reader.

**Comment by garak** [comment]
> Just saying: `doctrine/annotations` de-facto marked as deprecated: "library is considered feature complete, and should receive exclusively bugfixes and security fixes.", there are no guarantees that library will work with newer PHP versions and other requirements. IMO we should replace it as soon as possible with own independent implementation of metadata reader.

It doesn't seem so urgent to me.
Support for annotations in v2 is only meant to ease upgrading from v1. We can deprecate it in the next minor release, but we can't remove it before the next major, which it's not even planned (and likely won't happen before next year).

**Comment by k0d3r1s** [comment]
can you at least mention need for doctrine/annotations somewhere? as in v2 here attribute is default configuration which DOES NOT WORK if annotations package is missing. Or do it symfony way, like throwing exception that package is missing when using attribute/annotation and package is not there?  
i get that it needs to be solved properly but don't let people down just because you don't have time/resources/whatever to solve it. that is rediculous, your bundle is used by a lot of people

**Comment by garak** [comment]
> can you at least mention need for doctrine/annotations somewhere? 

It's mentioned here. I also pinned this issue this morning.

**Comment by k0d3r1s** [comment]
maybe in docs somewhere? or name this issue better? i didn't upgrade doctrine to anything, i just installed your package. title of this issue does not suggest people that is like mandatory reading or something.  
also this issue is about v2 of this package but same issue is present in v1 as well

**Comment by feymo** [comment]
@k0d3r1s This issue could be present in v1 as well since it's caused by the version of the `doctrine-bundle` you're using (>= 2.8). 😞 
I've just opened a PR with a documentation update & a suggestion added in `composer.json` so developpers can be aware of the "conflict" until we find a way to solve the problem. 🤞🏼

**Comment by andyexeter** [comment]
As well as adding doctrine/annotations as a suggestion in composer.json, I think it'd be nice for DX  use the container's `willBeAvailable` method and throw an exception during compilation if the configuration is set to use attributes or annotations and `doctrine/annotations` isn't installed.

**Comment by garak** [comment]
@sc0rp10 could you please check it the linked pull request is solving the problem?

**Comment by louismariegaborit** [comment]
Any release soon ?

**Comment by garak** [comment]
> Any release soon ?

I hope for the next weekend
