### ISSUE TITLE
add the generated id to the filename

### ISSUE THREAD

**Issue by matteosister** [dustin10/VichUploaderBundle#14]
By now it's not possible to give the Document (or Entity) a filename with the generated id. This is because the events is prePersist.

Are there any problems by changing prePersist to postPersist? (preUpdate is fine)
I could send you a PR. Maybe we should also add a parameter to let the user decide which lifecycle callback to use, and default to prePersist, so it won't break compatibility.

Let me know....

**Comment by grekpg** [comment]
Any plans to fix this issue?

**Comment by K-Phoen** [comment]
Not for the 1.0.x release, no. Maybe after.

**Comment by slimit** [comment]
What about PostPersist ?

**Comment by K-Phoen** [comment]
PostPersist would require the entity to be persisted twice (once to generate an auto-incremented ID and a second time to generate the filename). That's simply not an option.

If you really want to use the ID of your entity, generating one in PHP is your best shot (see [this comment](https://github.com/dustin10/VichUploaderBundle/issues/473#issuecomment-158808635))

**Comment by garak** [comment]
Simple solution: DO NOT USE an auto-increment for your id. Use something that is *predictable* and you're done. Examples: [UUID](https://github.com/ramsey/uuid) or [ShortId](https://github.com/PUGX/shortid-doctrine-bundle).

**Comment by spackmat** [comment]
@garak that doesn't answer any of my questions. I wouldn't have asked if this was an option for me or the other folks asking for ID-based-directories over and over again.

**Comment by garak** [comment]
I'm sorry but we can't add complexity just to fit in poor implementations

**Comment by spackmat** [comment]
OK, then I have to reimplement my upload without this bundle.

So could you at least be so kind and document this strong opinionated decision prominently? So that other folks with poor implementations don't step into this funny little boobie trap again. This could stop all those new issues opened here regarding ID based directories.

**Comment by garak** [comment]
Feel free to propose a PR for documentation

**Comment by spackmat** [comment]
No thanks, already wasted too much time with this bundle.

**Comment by Seb33300** [comment]
> I'm sorry but we can't add complexity just to fit in poor implementations

Auto increment is still the default behavior when creating entities with Symfony, and this is what most of the projects are using.
UUID is just an alternative, and not necessary a better implementation.

I can understand that adding support for auto increment can be quite complex and not really efficient in terms of performance.
But IMO, this is worth it to support it. Because this is a very common use case and this can simplify the life for many of us.

**Comment by garak** [comment]
@Seb33300 I understand that using autoincrement IDs can be an acceptable tradeoff.
But using such IDs for other than keys and relations is not.

**Comment by stefankleff** [comment]
I want to share my solution for some id generation strategies (autoincrement is NOT working).
We#re using UUIDs for the PK and this works fine:

https://gist.github.com/stefankleff/a4e0a2f546f5526cec3678213b829d06
