### ISSUE TITLE
Multiple files for the same entity?

### ISSUE THREAD

**Issue by radutopala** [dustin10/VichUploaderBundle#50]
Is there a way to add multiple files for the same entity, through specific bundle configuration?

Thanks.

**Comment by PeterFour** [comment]
I'm reopening the issue because I have the same problem and I wonder it this is intended behaviour or is fixed ?

The first name field is properly assigned, however the second one (or third one for that matter) will stay null causing SQL to fail.

Do we have to use separate nameer everytime we have more than one field ?
