### ISSUE TITLE
$file in downloadhelper is always null,

### ISSUE THREAD

**Issue by djgreg13** [dustin10/VichUploaderBundle#774]
Hello,

I try to serve a file by a controller, but type Mime is always application/octet-stream

After xdebug the solution, i found the $file attribute of downloadHandler is always null

```
if (true === $fileName) {
            $fileName = $mapping->readProperty($object, 'originalName');
        }

        $file = $mapping->getFile($object);
```

My entity : 

```
<?php

namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Vich\UploaderBundle\Entity\File as EmbeddedFile;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * Candidature
 *
 * @ORM\Table(name="candidature")
 * @ORM\Entity(repositoryClass="AppBundle\Repository\CandidatureRepository")
 * @Vich\Uploadable
 */
class Candidature
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="date_updated", type="datetime")
     */
    private $dateUpdated;

    /**
     * NOTE: This is not a mapped field of entity metadata, just a simple property.
     * 
     * @Vich\UploadableField(mapping="candidature_file", fileNameProperty="file.name", size="file.size", mimeType="file.mimeType", originalName="file.originalName")
     * 
     * @var File
     */
    private $fileFile;

    /**
     * @ORM\Embedded(class="Vich\UploaderBundle\Entity\File")
     *
     * @var EmbeddedFile
     */
    private $file;



    public function __construct(){
        $this->dateUpdated = new \DateTime('NOW');
        $this->file = new EmbeddedFile();
    }


    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * If manually uploading a file (i.e. not using Symfony Form) ensure an instance
     * of 'UploadedFile' is injected into this setter to trigger the  update. If this
     * bundle's configuration parameter 'inject_on_load' is set to 'true' this setter
     * must be able to accept an instance of 'File' as the bundle will inject one here
     * during Doctrine hydration.
     *
     * @param File|UploadedFile $file
     */
    public function setFileFile(File $file = null)
    {
        $this->fileFile = $file;

        if ($file) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->dateUpdated = new \DateTimeImmutable();
        }

        return $this;
    }

    /**
     * @return File|null
     */
    public function getFileFile()
    {
        return $this->fileFile;
    }

    /**
     * @param EmbeddedFile $image
     */
    public function setFile(EmbeddedFile $file)
    {
        $this->file = $file;

        return $this;
    }

    /**
     * @return EmbeddedFile
     */
    public function getFile()
    {
        return $this->file;
    }
}
```

My controller

```
/** 
     * Serves an uploaded file.
     *
     * @Route("/{id}/file", name="candidature_file")
     */
    public function fileAction(Candidature $candidature)
    {   
        $downloadHandler = $this->get('vich_uploader.download_handler');

        return $downloadHandler->downloadObject($candidature, $fileField = 'fileFile', Candidature::class, true);
    } 
```

**Comment by garak** [comment]
The 4th argument for `downloadObject` is a string, not a boolean.
See https://github.com/dustin10/VichUploaderBundle/blob/master/Resources/doc/downloads/serving_files_with_a_controller.md#renaming-files

**Comment by djgreg13** [comment]
According to phpdoc attached to downloadObject method, pass true at 4th argument take fileName from db
```
    /**
     * Create a response object that will trigger the download of a file.
     *
     * @param object|array $object
     * @param string       $field
     * @param string       $className
     * @param string|true  $fileName  True to return original file name
     *
     * @return StreamedResponse
     */
```

**Comment by guillaume-ro-fr** [comment]
Hello @djgreg13,

I have exactly the same problem...
You solved it ? 😄

Thanks

**Comment by mike240se** [comment]
> Hello,
> 
> I don't know why `$mapping->getFile($object)` returns `null`, but the only usage of `$file` is to get the mime type here :
> 
> ```
> return $this->createDownloadResponse(
>     $stream,
>     $fileName ?: $mapping->getFileName($object),
>     null === $file ? null : $file->getMimeType()     // <-- HERE
> );
> ```
> Maybe you should just change the third argument by `$mapping->readProperty($object, 'mimeType')` like above for the filename ? (I tested it, it works)
> 
> Edit : ok I just notice there's a PR about that : #923

Can you elaborate on how you fixed this?  I am having this same problem which means it never shows PDF preview because it never shows the correct pdf mimetype to the browser.  for me $file is always null as well and I havent been able to figure out why.

**Comment by mike240se** [comment]
> The 4th argument for `downloadObject` is a string, not a boolean.
> See https://github.com/dustin10/VichUploaderBundle/blob/master/Resources/doc/downloads/serving_files_with_a_controller.md#renaming-files

any update on this issue?  i have the 4th argument set properly and forceDownload is not working.  from what i can tell my problem is also that the mimetype is null so the browser does not show the pdf;s in the browser.

**Comment by chapa** [comment]
@mike240se I managed to fix this in my code by manually setting the `Content-Type` header of the response :
```php
$response = $downloadHandler->downloadObject($myObject, 'imageFile');
$response->headers->set('Content-Type', $myObject->getImage()->getMimeType());
```
You also can set the `Content-Disposition` to your match your needs ;-)

**Comment by mike240se** [comment]
> @mike240se I managed to fix this in my code by manually setting the `Content-Type` header of the response :
> 
> ```
> $response = $downloadHandler->downloadObject($myObject, 'imageFile');
> $response->headers->set('Content-Type', $myObject->getImage()->getMimeType());
> ```
> 
> You also can set the `Content-Disposition` to your match your needs ;-)

Can you share more of the code?  what is $myObject?  i havent been able to get the mimetype from the file because $file = $mapping->getFile($object); always returns null.  i havent been able to figure out why, because everything works fine.

**Comment by mike240se** [comment]
Wow ok I feel a little silly.  The reason $file is null is because inject_on_load is FALSE by default in the config!  This must be set to ON for the $file to be available in DownloadHandler.php to get the mimetype!  I highly recommend adding to the instructions on inline download to tell people inject_on_load must be set to true for it to work....  Hope this helps the other people above.

**Comment by chapa** [comment]
Nice find, but it looks like a bad fix for this problem to my mind.

It could work in some cases, but will not in others like mine : I use flysystem as storage abstraction, configured with an adapter to persist the files in an OpenStack Swift container.\
When I set `inject_on_load` to `true`, it does inject the file so the return of `$mapping->getFile($object)` is not `null`, but the `File` returned contains wrong data : the pathname is the path of the file on the Swift container, so when the `$file->getMimeType()` is executed I get a "The file xxx does not exist" because he tries to read the file on the local filesystem.

Anyway I think it's not a good idea to go this way because the model object already have the mime type information, so why do we need to guess it by reading the file ?\
The PR #923 resolves this by reading the previously saved mime type before trying to guess the mime type of the real file.

And to answer your question @mike240se, `$myObject` is the model object on which you [link the upload mapping](https://github.com/dustin10/VichUploaderBundle/blob/master/Resources/doc/usage.md#step-2-link-the-upload-mapping-to-an-entity).\
But maybe I should have mentioned that i use the `DownloadHandler` directly in a controller. I don't know if you are doing that or not so my "fix" may not be appropriate for you (?)

At least, if reading the file to guess the mime type is not a problem to you, you can use `inject_on_load` without problem. But I don't think it's the case for everyone so I'm not sure that adding an instruction in the doc is a good idea ;-)

**Comment by wietsewarendorff** [comment]
Hi, having almost the same problem since I switched to flysystem for storage, `inject_on_load` is set to `true` and a custom filenamer.

When I dump the contents of `$file` within the `downloadObject()`-method (here: https://github.com/dustin10/VichUploaderBundle/blob/master/Handler/DownloadHandler.php#L43):

```
File {#1153 ▼
  path: ""
  filename: "image.jpeg"
  basename: "image.jpeg"
  pathname: "image.jpeg"
  extension: "jpeg"
  realPath: false
  writable: false
  readable: false
  executable: false
  file: false
  dir: false
  link: false
}
```
Note: the path is empty, therefore the `$mapping->getFile($object)` will throw a `Symfony\Component\HttpFoundation\File\Exception\FileNotFoundException`.

Since the `$stream`-object is valid and contains the proper file (and path), I fixed this now by catching the exception and resetting the mimetype to null:

```
try {
    $file = $mapping->getFile($object);
    $mimeType = $file->getMimeType();
} catch (FileNotFoundException $fileNotFoundException) {
    $mimeType = null;
}
```

It's just a workaround, but fixes my problem now.
